default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost #<%= ENV['POSTGRES_HOST'] %>
  port: 5432

development:
  <<: *default
  database: capstone_demoapp_development

test:
  <<: *default
  database: capstone_demoapp_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: capstone_demoapp_production
  #url: #<%= ENV['DATABASE_URL'] %>
